// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef pdf_dialog_h
#define pdf_dialog_h
#include <FL/Fl.H>
#include <FL/Fl_Multiline_Input.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
extern Fl_Choice *choice_interpreter;
extern Fl_Multiline_Input *interpreter_text;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#include <stdlib.h>
#include <FL/Fl_Box.H>
extern Fl_Choice *choice_export_format;
extern Fl_Choice *choice_colourspace;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *slider_resolution;
extern Fl_Choice *choice_aa_graphic;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *check_aa_text;
extern Fl_Choice *choice_aa_gridfit;
extern Fl_Choice *choice_viewer;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_choice_interpreter[];
extern Fl_Menu_Item menu_choice_export_format[];
extern Fl_Menu_Item menu_choice_colourspace[];
extern Fl_Menu_Item menu_choice_aa_graphic[];
extern Fl_Menu_Item menu_choice_aa_gridfit[];
extern Fl_Menu_Item menu_choice_viewer[];
void take_opts();
#endif
