/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "libgimp/stdplugins-intl.h"

GtkWidget* create_iol_window (void);
GtkWidget* create_load_file_select (void);
GtkWidget* create_save_file_selection (void);
GtkWidget* create_iol_help_window (void);
