/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
//#include "support.h"

#if 0
GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *hbox1;
  GtkWidget *bit_depth_label;
  GtkWidget *optionmenu1;
  GtkWidget *optionmenu1_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *Load;
  GtkWidget *Cancel;

  dialog1 = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (dialog1), "dialog1", dialog1);
  gtk_window_set_title (GTK_WINDOW (dialog1), "dialog1");
  gtk_window_set_policy (GTK_WINDOW (dialog1), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_object_set_data (GTK_OBJECT (dialog1), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (dialog1), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 10);

  bit_depth_label = gtk_label_new ("Bit Depth");
  gtk_widget_ref (bit_depth_label);
  gtk_object_set_data_full (GTK_OBJECT (dialog1), "bit_depth_label", bit_depth_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_depth_label);
  gtk_box_pack_start (GTK_BOX (hbox1), bit_depth_label, TRUE, TRUE, 0);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_ref (optionmenu1);
  gtk_object_set_data_full (GTK_OBJECT (dialog1), "optionmenu1", optionmenu1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (optionmenu1);
  gtk_box_pack_start (GTK_BOX (hbox1), optionmenu1, TRUE, FALSE, 0);


  optionmenu1_menu = gtk_menu_new ();


  glade_menuitem = gtk_menu_item_new_with_label ("1");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);

  glade_menuitem = gtk_menu_item_new_with_label ("2");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);

  glade_menuitem = gtk_menu_item_new_with_label ("3");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);

  glade_menuitem = gtk_menu_item_new_with_label ("4");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);

  glade_menuitem = gtk_menu_item_new_with_label ("5");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);

  glade_menuitem = gtk_menu_item_new_with_label ("6");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);

  glade_menuitem = gtk_menu_item_new_with_label ("7");
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);








  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), optionmenu1_menu);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_object_set_data (GTK_OBJECT (dialog1), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (dialog1), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  Load = gtk_button_new_with_label ("Load");
  gtk_widget_ref (Load);
  gtk_object_set_data_full (GTK_OBJECT (dialog1), "Load", Load,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Load);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), Load);
  GTK_WIDGET_SET_FLAGS (Load, GTK_CAN_DEFAULT);

  Cancel = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (Cancel);
  gtk_object_set_data_full (GTK_OBJECT (dialog1), "Cancel", Cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), Cancel);
  GTK_WIDGET_SET_FLAGS (Cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (Load), "clicked",
                      GTK_SIGNAL_FUNC (on_Load_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_Cancel_clicked),
                      NULL);

  return dialog1;
}
#endif

