// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "EventTesterWinClass.h"
#include "EventTester.hpp"

void EventTesterWinClass::cb_window__i(Fl_Window* o, void*) {
  o->hide();
WidgetWrapper::delete_wrapper(this);
}
void EventTesterWinClass::cb_window_(Fl_Window* o, void* v) {
  ((EventTesterWinClass*)(o->user_data()))->cb_window__i(o,v);
}

EventTesterWinClass::EventTesterWinClass() {
  Fl_Window* w;
  { Fl_Window* o = window_ = new Fl_Window(275, 155, "EventDebugger (Br2Hdr)");
    w = o;
    o->tooltip("Debugging and testing tool.");
    o->callback((Fl_Callback*)cb_window_, (void*)(this));
    { EventTester* o = new EventTester(5, 5, 265, 145);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      o->end();
    }
    o->end();
  }
}

EventTesterWinClass::~EventTesterWinClass() {
  delete window_;
}

Fl_Window* EventTesterWinClass::window() {
  return window_;
}
